"""inital tables

Revision ID: 8c42ee25f9cc
Revises: 
Create Date: 2026-08-10 13:33:47.359933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c42ee25f9cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farmer_name', sa.String(length=100), nullable=False, comment='Name of the farmer same as citizenship name'),
    sa.Column('district', sa.String(length=50), nullable=False, comment='District where land parcel is located'),
    sa.Column('citizenship_number', sa.String(length=50), nullable=False, comment='Offical citizen number of the applicant'),
    sa.Column('phone_number', sa.String(length=15), nullable=False, comment='Contact number for SMS delivery'),
    sa.Column('land_area_hectares', sa.Float(), nullable=False, comment='Land area in hectares'),
    sa.Column('land_type', sa.String(length=20), nullable=False, comment='Type of land parcel (Khet(irrigated), Bari(rain-fed), GharBari(homestead))'),
    sa.Column('land_grade', sa.String(length=20), nullable=False, comment='Fertility Grade of land parcel (Aabal(1st), Doyam(2nd), Sim(3rd), Chahar(4th))'),
    sa.Column('coop_income_monthly', sa.Numeric(precision=12, scale=2), nullable=False, comment='Monthly income of the farmer from cooperative farming'),
    sa.Column('remittance_monthly', sa.Numeric(precision=12, scale=2), nullable=True, comment='Monthly remittance received by the farmer'),
    sa.Column('remittance_channel', sa.String(length=20), nullable=False, comment='Channel through which remittance is received (IME, Prabhu, Hundi, None)'),
    sa.Column('requested_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Amount requested by the user in nrs'),
    sa.Column('lalpurja_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Structured fields extracted from lalpurja by DVA-kitta,owner,area,grade'),
    sa.Column('lalpurja_image_path', sa.String(length=255), nullable=True, comment='File path of uploaded lalpurja image processed by DVA '),
    sa.Column('consent_given', sa.Boolean(), nullable=False, comment='Whether the user has given consent for data processing'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status of the application (Pending, Processing, Completed, Rejected)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("land_grade IN ('Aabal','Doyam','Sim','Chahar')", name='ck_application_land_grade_valid'),
    sa.CheckConstraint("land_type IN ('Khet','Bari','Gharbari')", name='ck_application_land_type_valid'),
    sa.CheckConstraint("remittance_channel IN ('IME','Prabhu','Hundi','None')", name='ck_application_remittance_channel_valid'),
    sa.CheckConstraint("status IN ('pending','processing','completed','failed')", name='ck_application_status_valid'),
    sa.CheckConstraint('coop_income_monthly >= 0', name='check_coop_income_monthly_positive'),
    sa.CheckConstraint('land_area_hectares > 0', name='check_land_area_hectares_positive'),
    sa.CheckConstraint('remittance_monthly >= 0', name='check_remittance_monthly_positive'),
    sa.CheckConstraint('requested_amount > 0', name='check_requested_amount_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_citizenship_number'), 'applications', ['citizenship_number'], unique=False)
    op.create_index(op.f('ix_applications_district'), 'applications', ['district'], unique=False)
    op.create_index(op.f('ix_applications_farmer_name'), 'applications', ['farmer_name'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False, comment='Foreign key to the applications table'),
    sa.Column('agent_name', sa.String(length=20), nullable=False, comment='DVA / IIA / CSA / CA / OA'),
    sa.Column('input_snapshot', sa.JSON(), nullable=False, comment='Exact inputs this agent produced — frozen at time of execution'),
    sa.Column('output_snapshot', sa.JSON(), nullable=False, comment='Exact outputs this agent produced — frozen at time of execution'),
    sa.Column('notes', sa.Text(), nullable=False, comment='Any additional notes or comments from the agent'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("agent_name IN ('DVA', 'IIA', 'CSA', 'CA', 'OA')", name='ck_audit_log_agent_name_valid'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_agent_name'), 'audit_logs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_application_id'), 'audit_logs', ['application_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False, comment='Foreign key to the applications table'),
    sa.Column('score', sa.Float(), nullable=False, comment='BridgeScore 0-100: >=65 approved, 45-64 conditional approve, <45 decline'),
    sa.Column('recommendation', sa.String(length=30), nullable=False, comment='Recommendation based on the score (Approve, Conditional Approve, Decline)'),
    sa.Column('approved_amount', sa.Float(), nullable=False, comment='Calibrated loan amount in NRs — may differ from requested_amount'),
    sa.Column('top_factors', sa.JSON(), nullable=False, comment='Top SHAP feature contributions'),
    sa.Column('nepali_explanation', sa.Text(), nullable=False, comment='Plain Nepali explanation delivered via SMS and portal'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("recommendation IN ('Approve','Conditional Approve','Decline')", name='ck_decision_recommendation_valid'),
    sa.CheckConstraint('approved_amount >= 0', name='ck_decision_approved_amount_non_negative'),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_decision_score_range'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_application_id'), 'decisions', ['application_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisions_application_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_audit_logs_application_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_agent_name'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_farmer_name'), table_name='applications')
    op.drop_index(op.f('ix_applications_district'), table_name='applications')
    op.drop_index(op.f('ix_applications_citizenship_number'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
